### ISSUE TITLE
some example want

### ISSUE THREAD

**Issue by xiangxud** [viamrobotics/goutils#2]
Great and useful project. I'm looking for an application that implements grpc through webrtc datachannel. I want to realize file transfer. Is there an example in this regard， js or go，thanks

**Comment by edaniels** [comment]
I'll try and build something for you!

**Comment by xiangxud** [comment]
thanks, I found an example of file transfer in go grpc. You can see if it can be implemented quickly.
https://dev.to/techschoolguru/upload-file-in-chunks-with-client-streaming-grpc-golang-4loc & https://github.com/duysmile/grpc-upload-file

**Comment by edaniels** [comment]
Hey @xiangxud, I added https://github.com/viamrobotics/goutils/tree/main/rpc/examples/fileupload. Can you try using/running that?

**Comment by xiangxud** [comment]
this is not base on webrtc datachannel, I want to do something base yours!

**Comment by edaniels** [comment]
It is! When using this it will prefer webrtc!

**Comment by xiangxud** [comment]
when i make build ,error like follow, canyou help me

ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts.
    at makeSourceMapAndFinish (/home/develop/nightingale/src/modules/agent/web/goutils/rpc/examples/fileupload/frontend/node_modules/ts-loader/dist/index.js:53:18)
    at successLoader (/home/develop/nightingale/src/modules/agent/web/goutils/rpc/examples/fileupload/frontend/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/home/develop/nightingale/src/modules/agent/web/goutils/rpc/examples/fileupload/frontend/node_modules/ts-loader/dist/index.js:23:5)
 @ /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientChannel.ts 21:21-46
 @ /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/dial.ts
 @ /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/index.ts
 @ ./src/index.ts

ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts
/home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts 136:16-36
[tsl] ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts(136,17)
      TS2532: Object is possibly 'undefined'.

ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts
/home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts 137:19-39
[tsl] ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts(137,20)
      TS2532: Object is possibly 'undefined'.

ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts
/home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts 138:30-50
[tsl] ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts(138,31)
      TS2532: Object is possibly 'undefined'.

ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts
/home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts 138:30-60
[tsl] ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts(138,31)
      TS2345: Argument of type 'number' is not assignable to parameter of type 'string | string[]'.

ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts
/home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts 140:31-51
[tsl] ERROR in /home/develop/nightingale/src/modules/agent/web/goutils/rpc/js/src/ClientStream.ts(140,32)
      TS2532: Object is possibly 'undefined'.

**Comment by xiangxud** [comment]
I modify ClientStream.ts code ,it's work fine ,thank you very much ,i will going to research youre code for my app. 
                        statusCode = trailers.getStatus()?.getCode(); //trailers.getStatus().getCode();
			statusMessage = trailers.getStatus()?.getMessage();
			 let statuscodestr = statusCode?.toString();//trailers.getStatus()?.getCode().toString()
			if (statuscodestr !=undefined){
			  headers.set("grpc-status", statuscodestr);
			}
			// this okay?
			// let statusmsg = trailers.getStatus()?.getMessage();
			if (statusMessage !=undefined){
			  headers.set("grpc-message", statusMessage);	
			}
